# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
#  requirements:
#  - !type:RoleTimeRequirement
#    role: JobBorg
#    time: 54000  # 15 hrs
  whitelisted: true # starcup
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  applyTraits: false

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 # starcup: 2 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  applyTraits: false
